Repository KOSA-2nd-Team3/back-end, pull requests merged in 2025-07, with the labels that each got.

#50 refactor: 불필요한 코드 정리
  src/main/java/kosa/server/board/controller/PlatformController.java
  src/main/java/kosa/server/board/controller/PostController.java
  src/main/java/kosa/server/board/dto/response/PlatformPostResponseDto.java
  src/main/java/kosa/server/board/service/PlatformService.java
  src/main/java/kosa/server/board/service/PostService.java
Labels: refactor

#52 refactor: 불필요한 코드 정리, MyPageService -> DashboardService 변경 후 코드 이동
  src/main/java/kosa/server/board/controller/DashboardController.java
  src/main/java/kosa/server/board/controller/PlatformController.java
  src/main/java/kosa/server/board/controller/PostController.java
  src/main/java/kosa/server/board/repository/PartyMemberRepository.java
  src/main/java/kosa/server/board/repository/PlatformRepository.java
  src/main/java/kosa/server/board/repository/PostRepository.java
  src/main/java/kosa/server/board/service/DashboardService.java
  src/main/java/kosa/server/board/service/MyPageService.java
  src/main/java/kosa/server/board/service/PostService.java
  src/main/java/kosa/server/member/repository/jpa/MemberJpaRepository.java
Labels: fix, refactor

#54 feat: 닉네임 수정
  src/main/java/kosa/server/common/advice/GlobalExceptionHandler.java
  src/main/java/kosa/server/common/code/ErrorCode.java
  src/main/java/kosa/server/member/controller/MemberController.java
  src/main/java/kosa/server/member/dto/request/NicknameUpdateRequest.java
  src/main/java/kosa/server/member/exception/DuplicateNicknameException.java
  src/main/java/kosa/server/member/repository/jpa/MemberJpaRepository.java
  src/main/java/kosa/server/member/service/MemberService.java
Labels: feat

#63 refactor: GlobalExceptionHandler 리팩토링 및 커스텀 예외 통합 처리
  src/main/java/kosa/server/auth/controller/AuthController.java
  src/main/java/kosa/server/auth/exception/DuplicateEmailException.java
  src/main/java/kosa/server/auth/exception/DuplicateLoginIdException.java
  src/main/java/kosa/server/auth/exception/InvalidTokenException.java
  src/main/java/kosa/server/auth/exception/LoginFailedException.java
  src/main/java/kosa/server/auth/exception/PasswordMismatchException.java
  src/main/java/kosa/server/auth/exception/RoleNotFoundException.java
  src/main/java/kosa/server/auth/exception/TokenNotFoundException.java
  src/main/java/kosa/server/auth/oauth2/handler/LoginSuccessHandler.java
  src/main/java/kosa/server/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/kosa/server/auth/service/AuthService.java
  src/main/java/kosa/server/board/exception/AlreadyPartyJoinedException.java
  src/main/java/kosa/server/board/exception/PartyFullException.java
  src/main/java/kosa/server/board/exception/PartyMemberNotFoundException.java
  src/main/java/kosa/server/board/exception/PlatformNotFoundException.java
  src/main/java/kosa/server/board/exception/PostNotFoundException.java
  src/main/java/kosa/server/board/service/DashboardService.java
  src/main/java/kosa/server/board/service/PlatformService.java
  src/main/java/kosa/server/board/service/PostService.java
  src/main/java/kosa/server/chat/controller/ChatController.java
  src/main/java/kosa/server/chat/exception/ChatParticipantNotFoundException.java
  src/main/java/kosa/server/chat/exception/NotGroupChatException.java
  src/main/java/kosa/server/chat/exception/NotMemberOfChatRoomException.java
  src/main/java/kosa/server/chat/service/ChatService.java
  src/main/java/kosa/server/common/advice/GlobalExceptionHandler.java
  src/main/java/kosa/server/common/code/ErrorCode.java
  src/main/java/kosa/server/common/exception/MemberNotFoundException.java
  src/main/java/kosa/server/member/service/MemberService.java
  src/test/java/kosa/server/board/service/PostServiceConcurrencyTest.java
  src/test/java/kosa/server/board/service/PostServiceTest.java
Labels: fix

#92 docs: 리드미 파일 추가
  README.md
Labels: documentation
