Repository KOSA-2nd-Team3/back-end, pull requests merged in 2025-06, with the labels that each got.

#6 refactor: chat 코드 리팩토링
  src/main/java/kosa/server/board/repository/PartyMemberRepository.java
  src/main/java/kosa/server/chat/controller/ChatController.java
  src/main/java/kosa/server/chat/dto/ChatRoomListResDto.java
  src/main/java/kosa/server/chat/dto/PartyMemberResponseDto.java
  src/main/java/kosa/server/chat/repository/jpa/ChatRoomJpaRepository.java
  src/main/java/kosa/server/chat/repository/jpa/ReadStatusJpaRepository.java
  src/main/java/kosa/server/chat/service/ChatService.java
Labels: feat

#8 feat: 이메일 비동기 처리 및 프론트 연결 api 추가, 플랫폼 별 파티리스트 구인 글이 없을 때, 고정 값 수정
  src/main/java/kosa/server/ServerApplication.java
  src/main/java/kosa/server/board/controller/PostController.java
  src/main/java/kosa/server/board/dto/response/MailSendDto.java
  src/main/java/kosa/server/board/dto/response/MailTargetResponseDto.java
  src/main/java/kosa/server/board/dto/response/PlatformPostNullResponseDto.java
  src/main/java/kosa/server/board/repository/PartyMemberRepository.java
  src/main/java/kosa/server/board/service/PostService.java
  src/main/java/kosa/server/mail/controller/MailController.java
  src/main/java/kosa/server/mail/service/MailService.java
  src/test/java/kosa/server/mail/service/MailServiceTest.java
Labels: feat

#15 feat: 대시보드 이미지 로드 및 채팅방 이동 기능 추가
  src/main/java/kosa/server/board/dto/response/MyPostOneResponseDto.java
  src/main/java/kosa/server/board/service/PostService.java
  src/main/java/kosa/server/chat/controller/ChatController.java
  src/main/java/kosa/server/chat/dto/ChatRoomIdResponseDto.java
  src/main/java/kosa/server/chat/repository/jpa/ChatRoomJpaRepository.java
  src/main/java/kosa/server/chat/service/ChatService.java
Labels: feat

#17 fix: chat-controller 파라미터 누락 수정 및 기타
  src/main/java/kosa/server/chat/controller/ChatController.java
Labels: fix

#22 feat: post 날짜 정렬
  src/main/java/kosa/server/board/controller/PostController.java
  src/main/java/kosa/server/board/repository/PostRepository.java
  src/main/java/kosa/server/board/service/PostService.java
Labels: enhancement

#23 fix: 소셜 로그인 리다이렉트 문제 해결
  src/main/java/kosa/server/auth/controller/AuthController.java
  src/main/java/kosa/server/auth/oauth2/handler/LoginSuccessHandler.java
  src/main/java/kosa/server/auth/oauth2/handler/TempAuthStorage.java
  src/main/java/kosa/server/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/kosa/server/common/config/SecurityConfig.java
  src/main/java/kosa/server/common/security/user/CustomUserPrincipal.java
  src/main/java/kosa/server/member/entity/Member.java
Labels: fix

#30 fix: 상세 페이지 플랫폼 가격 소숫점 한자리 올림, 시작된 파티는 목록에서 안보이게 하기
  src/main/java/kosa/server/board/dto/response/PlatformPostResponseDto.java
  src/main/java/kosa/server/board/service/PostService.java
Labels: fix

#39 fix: 변경 횟수 제한 삭제, 시작된 파티 목록 안보이게, 소수점 한자리 올림
  src/main/java/kosa/server/board/dto/request/PostUpdateRequestDto.java
  src/main/java/kosa/server/board/entity/Post.java
  src/main/java/kosa/server/board/service/PostService.java
Labels: fix

#43 fix: 플랫폼 뷰에서 monthUnit이 아닌 durationMonth 사용
  src/main/java/kosa/server/board/dto/response/PlatformPostResponseDto.java
  src/main/java/kosa/server/board/service/PostService.java
Labels: fix

#45 fix: mail 받았을 때, 링크를 통해 사이트 접근
  src/main/java/kosa/server/board/service/PostService.java
Labels: fix
